version: '2'

services:
  neo4j:
    image:  neo4j:3.0
    ports:
     - 7474:7474
     - 7687:7687
    container_name:  neo4j
    network_mode:  host
    volumes:
     - '$HOME/neo4j/data:/data'

  friendsbook:
    image:  friendsbook
    build:  ./
    restart:  always
#    network_mode:  host
    container_name:  friendsbook
    depends_on:
      - neo4j
    ports:
      - 8080:8090
    expose:
      - 8090

  react-app:
    build: friendbook
    image: react
    restart: always
    container_name: react
  #  network_mode: host
    ports:
    - 8081:8081
    expose:
      - 8081

